/*
 * generated by Xtext 2.9.0
 */
package com.agcs.eim.datastore


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DatavaultStandaloneSetup extends DatavaultStandaloneSetupGenerated {

	def static void doSetup() {
		new DatavaultStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
