/*
 * generated by Xtext 2.9.0
 */
package com.agcs.eim.datastore


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DatavaultRuntimeModule extends AbstractDatavaultRuntimeModule {
}
