/*
 * generated by Xtext 2.9.0
 */
package com.agcs.eim.datastore.validation

import com.agcs.eim.datastore.datavault.Greeting
import com.agcs.eim.datastore.datavault.DatavaultPackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DatavaultValidator extends AbstractDatavaultValidator {
	
  public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(Greeting greeting) {
		if (!Character.isUpperCase(greeting.name.charAt(0))) {
			warning('Name should start with a capital', 
					DatavaultPackage.Literals.GREETING__NAME,
					INVALID_NAME)
		}
	}
	
}
